name: Curiosity Blog
description: "Senior PHP Developer and Linux System Administrator, Free Software Fan, Archy (On Way Trust User), Junior Game Developer"
url: https://erayaydin.github.io
download: "https://github.com/erayaydin/erayaydin.github.io/archive/master.zip"
social:
  github: erayaydin
  email: aydineray@mail.com
  facebook:
  twitter: erayaydi
  instagram:
  tumblr:
author:
  name: Curiosity Team
  bio: "We are the guys behind Curiosity"
  email: Note from oskikiboy: Getting custom mail domain. MAYBE.
  image: /assets/images/favicon.png
  github: oskikiboy
  facebook: errorXD
  twitter: DEV_Curiosity
  instagram:
  tumblr:
  show_on_post: true
system:
  fb_app: "272683263159070"
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
